teams:
- name: lf-employees
  maintainers:
  - hartm
  - ryjones
  - thelinuxfoundation
  members:
  - christinaharter
- name: tac
  maintainers:
  - brian-jarvis-aws
  members:
  - AdityaKoranga
  - SWilson4
  - ashman-p
  - maximilien
  - planetf1
  - sophieschmieg
  - ydoroz
- name: wg-algorithms-members
  maintainers:
  - christinaharter
- name: wg-security-members
  maintainers:
  - christinaharter
- name: wg-tooling-members
  maintainers:
  - christinaharter
  members:
  - n1ckl0sk0rtge
- name: wiki-members
  maintainers:
  - brian-jarvis-aws
  members:
  - AdityaKoranga
  - christinaharter
  - mkannwischer
  - n1ckl0sk0rtge
  - praveksharma
repositories:
- name: .github
  teams:
    tac: maintain
  visibility: public
- name: artwork
  teams:
    tac: maintain
  visibility: public
- name: documentation
  teams:
    tac: maintain
  visibility: public
- name: landscape
  teams:
    lf-employees: maintain
  visibility: public
- name: governance
  teams:
    tac: maintain
  visibility: public
- name: TAC
  teams:
    tac: maintain
    lf-employees: maintain
  visibility: public
- name: wg-algorithms
  teams:
    tac: maintain
    wg-algorithms-members: maintain
  visibility: public
- name: wg-security
  teams:
    tac: maintain
    wg-security-members: maintain
  visibility: public
- name: wg-tooling
  teams:
    tac: maintain
    wg-tooling-members: maintain
  visibility: public
- name: wiki
  teams:
    lf-employees: maintain
    tac: maintain
    wiki-members: maintain
  visibility: public
